[package]
name = "status-upstream"
version = "0.1.2-alpha"
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
env_logger = "0.9"
hex-literal = "0.3.3"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "serde_json", "socks", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
